#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# check if screen resized
xrandr

# start fluxbox
FLUXPID=$(ps -ef | grep fluxbox|grep -vE "start|grep"|awk '{print $2}')
if [ -n "$FLUXPID" ]; then
    echo "kill running fluxbox window mgr: $FLUXPID"
    kill $FLUXPID
fi
exec fluxbox
